### ISSUE TITLE
Testing on png images not working

### ISSUE THREAD

**Issue by thomasjv799** [TJ-IPLab/DNet#2]
For testing part I used the pretrained model and the png images as per eigen split. However I am getting Index Error:Index out of range error. 
I have added --png in the evaluate depth line, also it is still reading as jpg which i havent been able to convert.

**Comment by josephxue** [comment]
Hi 😀
The latest code fixed this issue. You can evaluate png files using --png flag now.
But it should be noted that evaluation result using png extension may be different from paper, as that in paper was evaluated under jpg extension.

**Comment by thomasjv799** [comment]
Is it necessary to do sampling factor for conversion? I am using colab to run it so those convert and parallel commands are not supported there, which is why I was trying to run with png images only.

**Comment by josephxue** [comment]
It's not necessary. We applied this conversion just because we follow the same setup from our based code monodepth2. The sampling factor may slightly influence network performance but not that much.

**Comment by thomasjv799** [comment]
Sir,
Is it possible to test this model on a custom image and get depth as well as scale from it using this model.  In paper there is some images with their depth and their scale of depth, how can it be demonstrated even just for KITTI image.
Monodepth2 has a small prediction example where using their model they are predicting the disparity map of  a random image, similar to that.

**Comment by josephxue** [comment]
OK.
I'll write an example recently, you will be informed in this issue when the code is finished.

**Comment by josephxue** [comment]
OK.
Recently I will work on an example for random image depth prediction.
But open another issue may be a better way to do so. If you don't have questions about png files, I'll close this issue.
