### ISSUE TITLE
How can I predict absolute depth values pixel wise for random images?

### ISSUE THREAD

**Issue by Bookman98** [TJ-IPLab/DNet#3]
Sir, how can I get the absolute depth array pixel-wise for a test image using this code. I need to get the real distance from the camera so for that, I need the real depth values but when I am running evaluate_depth.py, it is giving metrics output. So, if I test it on random images, how can I get the disparity map along with the scale factor to calculate the absolute depth values? I want to know about the random image absolute depth prediction.

**Comment by josephxue** [comment]
Hi
For this issue, I uploaded a small example to predict depth along with its scale using random image.
You can run depth_prediction_example.ipynb on Jupyter Notebook. 😊

**Comment by josephxue** [comment]
Close this issue due to 7-day inactivity
