### ISSUE TITLE
Example for Prediction using a custom image

### ISSUE THREAD

**Issue by thomasjv799** [TJ-IPLab/DNet#4]
Sir,
Is it possible to test this model on a custom image and get depth as well as scale from it using this model. In paper there is some images with their depth and their scale of depth, how can it be demonstrated even just for KITTI image.
Monodepth2 has a small prediction example where using their model they are predicting the disparity map of a random image, similar to that, a way to demonstrate on a unseen image and get their prediction along with the distance scale.

**Comment by josephxue** [comment]
Hi
Your issue was handled in Issue [#3](https://github.com/TJ-IPLab/DNet/issues/3#issuecomment-694657689).
If you find it helpful, please close this one. 😊

**Comment by thomasjv799** [comment]
Sir,
How good it can predict absolute depth with some useen images such as indoor objects, close-up images etc, where not much relevant data is availble?

**Comment by josephxue** [comment]
Unfortunately, we've not done experiments on your mentioned datasets. We mainly focus on out-door autonomous driving scenes.
Maybe you can test your own data using the latest uploaded code, but retrain or finetune will be needed. 😃

**Comment by thomasjv799** [comment]
thank you
