### ISSUE TITLE
Camera Height

### ISSUE THREAD

**Issue by thomasjv799** [TJ-IPLab/DNet#5]
How much deviation can we expect with varying camera height on custom image?

**Comment by josephxue** [comment]
Hi

We haven't done experiments about that. But you can try it on your own by simply modify cam_height in depth_prediction_example.ipynb. Hope this answer can help you with that.

**Comment by thomasjv799** [comment]
I did sometimes I am getting more than 100 percent deviation at a particular height to less than 5 percent deviation. I dont know why the model is behaving differently at particular heights.

**Comment by josephxue** [comment]
Camera pitch angle also influences the performance. In KITTI dataset, camera was installed parallel to the ground, so the ideal ground surface normal is [0, 1, 0]. But if there is camera pitch angle, ideal surface normal will be changed, so is there any severe camera pitch in your own data?

**Comment by thomasjv799** [comment]
Yes there is small pitch in the angle. What I was trying to do is given a custom image how good the model will predict the distance. So for this I incorporated Mask RCNN in to it. After detecting the object in the Picture and using Dnet Model to get depth array. I estimate the mean of the mask to get approximate depth. But the main issue is that with respect to the ground height for the same object the model is giving different depth values.

**Comment by josephxue** [comment]
Maybe I don't understand your question. For a same image, if you run multiple times for inference, the result will also be the same, because network will not give random outputs.  I wonder if you could send me one of your data, so I can test it too.

**Comment by thomasjv799** [comment]
Ofcourse.
Please have a look in this : https://github.com/wanderer799/DNet-Document

**Comment by josephxue** [comment]
Hi
Have you retrain the network before inference? Because from my perspective the images are quite different compared to  KITTI dataset. This network may not have that generalization ability to adapt different image domain without retraining.
By the way, could you please add relative depth map to the document too? Maybe the main issue is from relative depth estimation.

**Comment by thomasjv799** [comment]
No Sir, I didnt retrained the network I just used the pretrained model that was given. I thought of using NYU Dataset but I was researching a lot on absolute depth prediction and wasnt getting much promising result using Monodepth2.Your model is the best so far. So I thought of testing it first  I have added Disparity predictions Some maps are fine, some are bad. I have updated it. Please have a look.

**Comment by josephxue** [comment]
Hi
I checked your uploaded relative depth map, sorry to say that the result is not satisfied compared to inference using KITTI dataset. So maybe you can try to re-train the network, otherwise in my opinion there will not be a better way to improve the accuracy.

**Comment by thomasjv799** [comment]
Ok Sir. Let me try that. Thank you very much.

**Comment by mvpzhangqiu** [comment]
> Ok Sir. Let me try that. Thank you very much.

hey guy，did u retrain the network?How did it turn out？very curious about it.

**Comment by thomasjv799** [comment]
Yes, retraining helped improve the result further though I didn't have much data so result was only decent. The Camera height turned out to be important factor here.
