### ISSUE TITLE
Quertion about ‘’transformation_from_parameters‘’？

### ISSUE THREAD

**Issue by wqx854987945** [TJ-IPLab/DNet#8]
Hi!
As I know, the pose network only has to learn to predict transformations in one direction and get T-1→0 and T0→1, when inverting the camera-to-camera transformation matrix, your code is
'if invert: R=R.transpose(1,2) t*=-1'.
Question 1) : whether the code in the transformation should be 'if invert: R=R.transpose(1,2)，t=-np.dot(R, t)'?
 I look forward to your reply and correction！

**Comment by josephxue** [comment]
Hi!
After further consideration, I think both you and the code are right.
First I want to make it clear that the variable M is the transform matrix.
If not invert, the variable R represents a matrix like [R 0; 0<sup>T</sup> 1], the variable T represents a matrix like [I t; 0<sup>T</sup> 1], so the M matrix is [R t; 0<sup>T</sup> 1].
If invert, the variable R represents a matrix like [R<sup>T</sup> 0; 0<sup>T</sup> 1], the variable T represents a matrix like [I -t; 0<sup>T</sup> 1], so the M matrix is [R<sup>T</sup> -R<sup>T</sup>t; 0<sup>T</sup> 1].
So the code is consistent with your description.

**Comment by josephxue** [comment]
Close this issue due to 7-day inactivity.
